### ISSUE TITLE
IOS 打包相对路径问题

### ISSUE THREAD

**Issue by Eason-Wu** [Clouda-team/BlendUI#17]
IOS 打包发布使用的下面的网盘提供的xcode 工程
http://pan.baidu.com/s/1jGrAdLk

打包时发现项目根目录下 index页面引用资源 例如js或者css 时，使用相对路径， js/main.js css/main.css 或者 http://localhost/+dev+/js/main.js 等方式都无法引入JS 文件， 当去除相对路径直接使用 main.js 时，文档会自动搜索到当前文件， 无论文件的位置在哪儿。文档目录结构形同虚设。请问是否因为路径写错，还是 IOS 打包的runtime 就是如此规定的不需要相对地址。

**Comment by wwxcab** [comment]
在添加文件目录到Xcode项目的时候，选择 Create folder reference的方式（添加完成后Xcode中文件夹为蓝色）。如果误选了Create groups（添加完成后Xcode中文件夹为黄色），Xcode会把文件夹内的文件放到App运行目录的根目录，不会建立层级关系，这样就会出现你说的这个现象。

**Comment by Eason-Wu** [comment]
好的，我回去试一下 ，
